doctor/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'doctor'

urlpatterns = [
    path('accounts/login/', never_cache(views.login), name='login'),
    path('accounts/logout/', never_cache(views.logout), name='logout'),
    path('dashboard/', never_cache(views.index), name='dashboard'),
    path('submitted/<int:submittedid>', never_cache(views.submitted_item), name='submitted'),
    path('analysis/<int:pendingid>', never_cache(views.analysis), name='analysis'),
    path('analysis/result', never_cache(views.result), name="result"),
    path('analysis/eqHist', never_cache(views.equalize_hist), name="eq_hist"),
    path('analysis/print', never_cache(views.print_report), name="print"),
    path('analysis/detectEdge', never_cache(views.detect_edge), name="detect_edge"),
    path('analysis/changeThreshold', never_cache(views.change_threshold), name='changethreshold'),
    path('analysis/changeContrast', never_cache(views.change_contrast), name='changecontrast'),
]

home/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'home'

urlpatterns = [
    path('', never_cache(views.index), name='home'),
]

midas_final/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('assistant/', include('assistant.urls')),
    path('doctor/', include('doctor.urls')),
    path('patient/', include('patient.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

patient/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'patient'

urlpatterns = [
    path('accounts/login/', never_cache(views.login), name='login'),
    path('accounts/logout/', never_cache(views.logout), name='logout'),
    path('dashboard/', never_cache(views.index), name='dashboard'),
]

patient/models.py
from django.db import models


# Create your models here.
class PatientDetails(models.Model):
    userId = models.IntegerField(unique=True)
    name = models.CharField(max_length=25)
    email = models.EmailField(max_length=30)
    password = models.CharField(max_length=50)
    isActive = models.BooleanField(default=False)

    def __str__(self):
        return self.name + "(" + str(self.userId) + ")"

patient/forms.py
from django import forms


class PatientLogin(forms.Form):
    user_id = forms.IntegerField(label="User Id", required=True, min_value=1)
    password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput, min_length=8)

patient/views.py
from django.http import HttpResponsePermanentRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import PatientDetails
from doctor.models import DoctorDetails, PendingList, SubmittedList
from assistant.models import AssistantDetails
from .forms import PatientLogin


# Create your views here.

# Patient home
def index(request):
    patient_set = PatientDetails.objects.all()
    for patient in patient_set:
        if patient.isActive:
            pending_set = PendingList.objects.filter(patientId=patient)
            submitted_set = SubmittedList.objects.filter(patientId=patient)
            context = {"patient": patient, "pending": pending_set, "submitted": submitted_set}
            return render(request, 'patient/pages/dashboard.html', context)

    return HttpResponsePermanentRedirect(reverse('patient:login'))


# Login
def login(request):
    # Check if already logged in
    doctor_set = DoctorDetails.objects.all()
    for doctor in doctor_set:
        if doctor.isActive:
            return HttpResponsePermanentRedirect(reverse('doctor:dashboard'))

    assistant_set = AssistantDetails.objects.all()
    for assistant in assistant_set:
        if assistant.isActive:
            return HttpResponsePermanentRedirect(reverse('assistant:dashboard'))

    patient_set = PatientDetails.objects.all()
    for patient in patient_set:
        if patient.isActive:
            return HttpResponsePermanentRedirect(reverse('patient:dashboard'))

    # Get login Information
    if request.method == 'POST':
        form = PatientLogin(request.POST)

        if form.is_valid():
            for patient in patient_set:
                if patient.userId == form.cleaned_data['user_id'] and patient.password == \
                        form.cleaned_data['password']:
                    patient.isActive = True
                    patient.save()
                    return HttpResponsePermanentRedirect(reverse('patient:dashboard'))
        else:
            pass

    else:
        form = PatientLogin()

    return render(request, 'patient/registration/login.html', {'form': form})


# Logout
def logout(request):
    patient_set = PatientDetails.objects.all()
    for patient in patient_set:
        if patient.isActive:
            patient.isActive = False
            patient.save()
            return HttpResponsePermanentRedirect(reverse('home:home'))

    return HttpResponsePermanentRedirect(reverse('home:home'))

patient/templates/patient/pages/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Patient List</title>
    <link rel="stylesheet" type="text/css" href="{% static "patient/css/dashboard.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:home' %}">MIDAS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Dashboard for Patient</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <a class="nav-link" href="#" style="color: white">Welcome, {{ patient.name }}</a>
      <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'patient:logout' %}">Logout</a>
    </form>
  </div>
</nav>

    <br><br><br>

            <div class="container m-7 pb-5">
                    <div class="row">
                        <div class="col">
                            <h3 class="mt-2">Pending</h3>
                            <div class="list-group">
                                {% if pending.count %}
                                    {% for pending in pending %}
                                      <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                          <h5 class="mb-1">Type : {{ pending.type.name }}</h5>
                                          <small>{{ pending.date }}</small>
                                        </div>
                                          <p>
                                        <img src="{{ pending.images.url }}" style="width: 20%;height: 20%;" alt="Not found"/>
                                          </p>
                                      </a>
                                    {% endfor %}
                                {% else %}
                                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                          <h5 class="mb-1">Nothing to show</h5>
                                        </div>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col">
                            <h3 class="mt-2">Reported</h3>
                            <div class="list-group">
                                  {% if submitted.count %}
                                    {% for submitted in submitted %}
                                      <a href="{% url 'doctor:submitted' submitted.id %}" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                          <h5 class="mb-1">Type : {{ submitted.type.name }}</h5>
                                          <small>{{ submitted.date }}</small>
                                        </div>
                                          <p>
                                        <img src="{{ submitted.image.url }}" style="width: 20%;height: 20%;" alt="Not found"/>
                                          </p>
                                      </a>
                                    {% endfor %}
                                {% else %}
                                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                          <h5 class="mb-1">Nothing Reported</h5>
                                        </div>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
            </div>
</body>
</html>