doctor/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'doctor'

urlpatterns = [
    path('accounts/login/', never_cache(views.login), name='login'),
    path('accounts/logout/', never_cache(views.logout), name='logout'),
    path('dashboard/', never_cache(views.index), name='dashboard'),
    path('submitted/<int:submittedid>', never_cache(views.submitted_item), name='submitted'),
    path('analysis/<int:pendingid>', never_cache(views.analysis), name='analysis'),
    path('analysis/result', never_cache(views.result), name="result"),
    path('analysis/eqHist', never_cache(views.equalize_hist), name="eq_hist"),
    path('analysis/print', never_cache(views.print_report), name="print"),
    path('analysis/detectEdge', never_cache(views.detect_edge), name="detect_edge"),
    path('analysis/changeThreshold', never_cache(views.change_threshold), name='changethreshold'),
    path('analysis/changeContrast', never_cache(views.change_contrast), name='changecontrast'),
]

home/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'home'

urlpatterns = [
    path('', never_cache(views.index), name='home'),
]

midas_final/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('assistant/', include('assistant.urls')),
    path('doctor/', include('doctor.urls')),
    path('patient/', include('patient.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

doctor/models.py
from django.db import models
from patient.models import PatientDetails

# Create your models here.


class DoctorDetails(models.Model):
    userId = models.IntegerField(unique=True)
    name = models.CharField(max_length=25)
    email = models.EmailField(max_length=30)
    password = models.CharField(max_length=50)
    isActive = models.BooleanField(default=False)

    def __str__(self):
        return self.name + "(" + str(self.userId) + ")"


class Types(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return str(self.name)


def content_file_name_pending(instance, filename):
    return '/'.join(["images", str(instance.doctorId.userId), "pending", str(instance.patientId), str(instance.type),
                     str(filename)])


def content_file_name_submitted(instance, filename):
    return '/'.join(["images", str(instance.doctorId.userId), "submitted", str(instance.patientId), str(instance.type),
                     str(filename)])


class PendingList(models.Model):
    doctorId = models.ForeignKey(DoctorDetails, on_delete=models.CASCADE)
    patientId = models.ForeignKey(PatientDetails, on_delete=models.CASCADE)
    type = models.ForeignKey(Types, on_delete=models.CASCADE)
    images = models.ImageField(upload_to=content_file_name_pending)
    date = models.DateTimeField(auto_now_add=True)


class SubmittedList(models.Model):
    doctorId = models.ForeignKey(DoctorDetails, on_delete=models.CASCADE)
    patientId = models.ForeignKey(PatientDetails, on_delete=models.CASCADE)
    type = models.ForeignKey(Types, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=content_file_name_submitted)
    report = models.CharField(max_length=250)
    date = models.DateTimeField(auto_now_add=True)

doctor/forms.py
from django import forms


class DoctorLogin(forms.Form):
    user_id = forms.IntegerField(label="User Id", required=True, min_value=1)
    password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput, min_length=8)


class ReportForm(forms.Form):
    report = forms.CharField(widget=forms.Textarea(attrs={'cols': 80, 'rows': 5}))

doctor/views.py
from time import sleep

from django.http import HttpResponsePermanentRedirect, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import DoctorLogin, ReportForm
from .models import DoctorDetails, SubmittedList, PendingList
from assistant.models import AssistantDetails
from patient.models import PatientDetails

from classifiers.chest_X_ray_view_classifier import main

import os
import cv2
import shutil
import numpy as np
from .detect import ultimo

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Create your views here.

# Doctor Home
def index(request):
    doctor_set = DoctorDetails.objects.all()
    for doctor in doctor_set:
        if doctor.isActive:
            pending_set = PendingList.objects.filter(doctorId=doctor)
            submitted_set = SubmittedList.objects.filter(doctorId=doctor)
            context = {'doctor': doctor, 'pending': pending_set, 'submitted': submitted_set}
            # print(context)
            return render(request, 'doctor/pages/dashboard.html', context)

    return HttpResponsePermanentRedirect(reverse('doctor:login'))


# Doctor Login
def login(request):
    # Check Previous Login
    doctor_set = DoctorDetails.objects.all()
    for doctor in doctor_set:
        if doctor.isActive:
            return HttpResponsePermanentRedirect(reverse('doctor:dashboard'))

    assistant_set = AssistantDetails.objects.all()
    for assistant in assistant_set:
        if assistant.isActive:
            return HttpResponsePermanentRedirect(reverse('assistant:dashboard'))

    patient_set = PatientDetails.objects.all()
    for patient in patient_set:
        if patient.isActive:
            return HttpResponsePermanentRedirect(reverse('patient:dashboard'))

    if request.method == 'POST':
        form = DoctorLogin(request.POST)

        if form.is_valid():
            for doctor in doctor_set:
                if doctor.userId == form.cleaned_data['user_id'] and doctor.password == form.cleaned_data['password']:
                    doctor.isActive = True
                    doctor.save()
                    return HttpResponsePermanentRedirect(reverse('doctor:dashboard'))
        else:
            pass

    else:
        form = DoctorLogin()

    return render(request, 'doctor/registration/login.html', {'form': form})


# Doctor Logout
def logout(request):
    doctor_set = DoctorDetails.objects.all()
    for doctor in doctor_set:
        if doctor.isActive:
            doctor.isActive = False
            doctor.save()
            return HttpResponsePermanentRedirect(reverse('home:home'))

    doctor_set = PatientDetails.objects.all()
    for doctor in doctor_set:
        if doctor.isActive:
            doctor.isActive = False
            doctor.save()
            return HttpResponsePermanentRedirect(reverse('home:home'))

    doctor_set = AssistantDetails.objects.all()
    for doctor in doctor_set:
        if doctor.isActive:
            doctor.isActive = False
            doctor.save()
            return HttpResponsePermanentRedirect(reverse('home:home'))

    return HttpResponsePermanentRedirect(reverse('home:home'))


def getdirectorystuffs(pendingitem):
    IMAGE_DIR = "/".join(BASE_DIR.split("\\")) + str(pendingitem.images.url)
    IMAGE_DIR_ROOT = "/".join(str(pendingitem.images.url).split("/")[0:-1])
    DIR_ROOT = "/".join(IMAGE_DIR.split("/")[0:-1])
    IMAGE_NAME = str(pendingitem.images.name).split("/")[-1]
    TEMP_NAME = "temp_" + str(pendingitem.images.name).split("/")[-1]
    TEMP_IMAGE_DIR = "/".join(BASE_DIR.split("\\")) + IMAGE_DIR_ROOT + "/" + TEMP_NAME
    TEMP_IMAGE_SRC = IMAGE_DIR_ROOT + "/" + TEMP_NAME

    return {"IMAGE_DIR": IMAGE_DIR, "IMAGE_DIR_ROOT": IMAGE_DIR_ROOT, "TEMP_NAME": TEMP_NAME,
            "TEMP_IMAGE_DIR": TEMP_IMAGE_DIR, "TEMP_IMAGE_SRC": TEMP_IMAGE_SRC, "IMAGE_NAME": IMAGE_NAME,
            "DIR_ROOT": DIR_ROOT}


# Analysis The Patient's Pending Item
def analysis(request, pendingid):
    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            pendingitem = PendingList.objects.get(id=pendingid)
            submitteditem = SubmittedList()
            submitteditem.doctorId, submitteditem.patientId, submitteditem.type = pendingitem.doctorId, pendingitem.patientId, pendingitem.type
            NEW_DIR = "/".join(str(pendingitem.images.url).replace("pending", "submitted").split("/")[2:])
            CUR_DIR = getdirectorystuffs(pendingitem)["DIR_ROOT"].replace("pending", "submitted")
            submitteditem.image = NEW_DIR
            submitteditem.report = form.cleaned_data['report']
            if os.path.exists(CUR_DIR):
                shutil.rmtree(CUR_DIR)
            os.makedirs(CUR_DIR)
            shutil.move(getdirectorystuffs(pendingitem)["IMAGE_DIR"], CUR_DIR)
            os.remove(getdirectorystuffs(pendingitem)["TEMP_IMAGE_DIR"])
            submitteditem.save()
            pendingitem.delete()

            return HttpResponsePermanentRedirect(reverse('doctor:dashboard'))

        else:

            return HttpResponsePermanentRedirect(reverse('doctor:dashboard'))

    try:
        pendingitem = PendingList.objects.get(id=pendingid)
    except:
        return HttpResponsePermanentRedirect(reverse('doctor:dashboard'))

    form = ReportForm()
    context = {'pendingItem': pendingitem, 'form': form}

    # READ WRITE IMAGE #
    img = cv2.imread(getdirectorystuffs(pendingitem)["IMAGE_DIR"], 0)
    cv2.imwrite(getdirectorystuffs(pendingitem)["TEMP_IMAGE_DIR"], img)

    # print(pendingitem.images.url)
    if pendingitem.type.name in ["chest", "Pneumonia"]:
        return render(request, 'doctor/pages/chestanalysis.html', context)
    elif pendingitem.type.name in ['elbow', 'finger', 'forearm', 'hand', 'humerus', 'shoulder', 'wrist']:
        return render(request, 'doctor/pages/msd.html', context)
    elif pendingitem.type.name in ["mammography"]:
        return render(request, 'doctor/pages/mammography.html', context)

    return HttpResponse("In Analysys")


# Return The Result After Analysis
def result(request):
    if request.method == "GET":
        pending_id = int(request.GET.get('id'))
        type = str(request.GET.get('type'))
    else:
        return HttpResponsePermanentRedirect(reverse('doctor:dashboard'))

    try:
        pendingitem = PendingList.objects.get(id=pending_id)
    except:
        return HttpResponsePermanentRedirect(reverse('doctor:dashboard'))

    if type in ["chest", "Pneumonia"]:
        img_pneum = cv2.imread(getdirectorystuffs(pendingitem)["IMAGE_DIR"], 0)
        img_lung = cv2.imread(getdirectorystuffs(pendingitem)["IMAGE_DIR"])
        dic = ultimo(img_pneum, img_lung)
        cv2.imwrite(getdirectorystuffs(pendingitem)["TEMP_IMAGE_DIR"], dic['pneum'])
        score, final_report = dic['report']
        final_report = "" + score + "<br/>" + final_report
        return HttpResponse(final_report+"?"+getdirectorystuffs(pendingitem)["TEMP_IMAGE_SRC"])
    elif type in ["lung"]:
        img_pneum = cv2.imread(getdirectorystuffs(pendingitem)["IMAGE_DIR"], 0)
        img_lung = cv2.imread(getdirectorystuffs(pendingitem)["IMAGE_DIR"])
        # img_pneum = cv2.imread('I:\\updated\\midas_final\\media\images\\1\\pending\\Asif(1)\\Pneumonia\\img_1.jpg', 0)
        # img_lung = cv2.imread('I:\\updated\\midas_final\\media\images\\1\\pending\\Asif(1)\\Pneumonia\\img_1.jpg')
        dic = ultimo(img_pneum, img_lung)
        cv2.imwrite(getdirectorystuffs(pendingitem)["TEMP_IMAGE_DIR"], dic['lung'])
        return HttpResponse(" " + "?" + getdirectorystuffs(pendingitem)["TEMP_IMAGE_SRC"])
    elif type in ["position"]:
        result = main.view_predict(getdirectorystuffs(pendingitem)["IMAGE_DIR"])
        return HttpResponse(result)
    elif type in ['elbow', 'finger', 'forearm', 'hand', 'humerus', 'shoulder', 'wrist']:
        context = {"abnormal_XR_ELBOW_hist_276.png": ['Abnormal', 'Elbow_Result_of_VGG_Model1.txt', 'XR_ELBOW'],
                   "normal_XR_ELBOW_hist_13.png": ['Normal', 'Elbow_Result_of_VGG_Model2.txt', 'XR_ELBOW'],
                   "abnormal_XR_FINGER_hist_422.png": ['Abnormal', 'Finger_Result_of_VGG_Model1.txt', 'XR_FINGER'],
                   "normal_XR_FINGER_hist_82.png": ['Normal', 'Finger_Result_of_VGG_Model2.txt', 'XR_FINGER'],
                   "abnormal_XR_FOREARM_hist_231.png": ['Abnormal', 'Forearm_Result_of_VGG_Model1.txt', 'XR_FOREARM'],
                   "normal_XR_FOREARM_hist_109.png": ['Normal', 'Forearm_Result_of_VGG_Model.txt2', 'XR_FOREARM'],
                   "abnormal_XR_HAND_hist_348.png": ['Abnormal', 'Hand_Result_of_VGG_Model.txt1', 'XR_HAND'],
                   "normal_XR_HAND_hist_155.png": ['Normal', 'Hand_Result_of_VGG_Model2.txt', 'XR_HAND'],
                   "abnormal_XR_HUMERUS_hist_267.png": ['Abnormal', 'Humerus_Result_of_VGG_Model1.txt', 'XR_HUMERUS'],
                   "normal_XR_HUMERUS_hist_68.png": ['Normal', 'Humerus_Result_of_VGG_Model2.txt', 'XR_HUMERUS'],
                   "abnormal_XR_SHOULDER_hist_240.png": ['Abnormal', 'Shoulder_Result_of_VGG_Model1.txt', 'XR_SHOULDER'],
                   "normal_XR_SHOULDER_hist_13.png": ['Normal', 'Shoulder_Result_of_VGG_Model2.txt', 'XR_SHOULDER'],
                   "abnormal_XR_WRIST_hist_422.png": ['Abnormal', 'Wrist_Result_of_VGG_Model1.txt', 'XR_WRIST'],
                   "normal_XR_WRIST_hist_64.png": ['Normal', 'Wrist_Result_of_VGG_Model2.txt', 'XR_WRIST']}

        if getdirectorystuffs(pendingitem)['IMAGE_NAME'] in context:
            report = open("/home/asifurarahman/midas_final/midas_final/media/classifiers/Musculoskeletal/" +
                          context[getdirectorystuffs(pendingitem)['IMAGE_NAME']][2] + "/" +
                          context[getdirectorystuffs(pendingitem)['IMAGE_NAME']][1], "r+")

            msd_type = context[getdirectorystuffs(pendingitem)['IMAGE_NAME']][0]

            final_report = ""

doctor/templates/doctor/pages/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Patient List</title>
    <link rel="stylesheet" type="text/css" href="{% static "patient/css/dashboard.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:home' %}">MIDAS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Dashboard for Doctor</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a class="nav-link" href="#" style="color: white">Welcome, {{ doctor.name }}</a>
      <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'doctor:logout' %}">Logout</a>
    </form>
  </div>
</nav>


    <br><br><br>
            <div class="container m-7 pb-5">
                    <div class="row">
                        <div class="col">
                            <h3 class="mt-2">Pending</h3>
                            <div class="list-group">
                                {% if pending.count %}
                                    {% for pending in pending %}
                                      <a href="{% url 'doctor:analysis' pending.id %}" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                          <h5 class="mb-1">Type : {{ pending.type.name }}</h5>
                                          <small>{{ pending.date }}</small>
                                        </div>
                                          <p class="mb-1">Name : {{ pending.patientId.name }}</p>
                                          <p>
                                        <img src="{{ pending.images.url }}" style="width: 20%;height: 20%;" alt="Not found"/>
                                          </p>
                                      </a>
                                    {% endfor %}
                                {% else %}
                                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                          <h5 class="mb-1">Nothing to show</h5>
                                        </div>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col">
                            <h3 class="mt-2">Reported</h3>
                            <div class="list-group">
                                  {% if submitted.count %}
                                    {% for submitted in submitted %}
                                      <a href="{% url 'doctor:submitted' submitted.id %}" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                          <h5 class="mb-1">Type : {{ submitted.type.name }}</h5>
                                          <small>{{ submitted.date }}</small>
                                        </div>
                                          <p class="mb-1">Name : {{ submitted.patientId.name }}</p>
                                          <p>
                                        <img src="{{ submitted.image.url }}" style="width: 20%;height: 20%;" alt="Not found"/>
                                          </p>
                                      </a>
                                    {% endfor %}
                                {% else %}
                                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                          <h5 class="mb-1">Nothing Reported</h5>
                                        </div>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
            </div>
</body>
</html>

doctor/templates/doctor/pages/mammography.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load crispy_forms_tags %}
<head>
    <meta charset="UTF-8">
    <title>Chest Analysis</title>
    <link rel="stylesheet" type="text/css" href="{% static 'doctor/css/analysis.css' %}">
    <link rel="stylesheet" href="{% static 'doctor/css/slider.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        function getId(id = {{ pendingItem.id }}){
            return id;
        }
        function getType(type = "{{ pendingItem.type }}") {
            return type;
        }
    </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:home' %}">MIDAS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'doctor:logout' %}">Logout</a>
    </form>
  </div>
</nav>

    <br><br>

            <div class="container m-7 pb-5">
                    <div class="row">
                        <div class="col">
                            <h3 class="mt-2">Mammography Image</h3>
                            <div class="list-group">
                                      <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <img id="myImg" src="{{ pendingItem.images.url }}" style="width: 100%;height: 100%" alt="Not found"/>
                                      </a>
                            </div>
                            <br>
                            <div style="margin-left: 35%;">
                                <a class="btn btn-info" style="width: 140px;" href="{{ pendingItem.images.url }}">Original Size</a>
                            </div>
                        </div>
                        <div class="col">
                            <h3 class="mt-2">Tools</h3>
                            <div class="list-group">
                                      <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                            <p id="amount" style="border:0; font-weight:bold;">Threshold range : 0 - 255</p>
                                        </div>

                                          <div id="slider-range" style="width: 100%;"></div>

                                      </a>
                                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                            <p id="alpha" style="border:0; font-weight:bold;">Alpha : 1</p>
                                        </div>
                                        <div id="slider-range-alpha" style="width: 100%;"></div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-between">
                                            <p id="beta" style="border:0; font-weight:bold;">Beta : 0</p>
                                        </div>
                                        <div id="slider-range-beta" style="width: 100%;"></div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-center">
                                            <button onclick="detectEdgeFun()" class="btn btn-info" style="width: 40%;">Detect Edges</button>
                                        </div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-center">
                                            <button onclick="eqHistFun()" class="btn btn-info" style="width: 40%;">Equalize Histogram</button>
                                        </div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-center">
                                            <button onclick="getResultFun()" class="btn btn-info" style="width: 40%;">Detect Mammography</button>
                                        </div>
                                        <p>
                                        <p id="mammography"></p>
                                        <p id="mamconfidence"></p>
                                    </a>
                                <a href="#" class="list-group-item list-group-item-action flex-column align-items-start list-group-item-secondary">
                                        <div class="d-flex w-100 justify-content-center">
                                        </div>
                                        <p>
                                            <form method="post">

                                                {% csrf_token %}

                                                        <div id="div_id_report" class="form-group">

                                                                <label for="id_report" class="col-form-label  requiredField">
                                                                    <b>Report</b><span class="asteriskField">*</span>
                                                                </label>

                                                                    <div class="">
                                                                        <textarea name="report" cols="80" rows="5" class="textarea form-control" required id="id_report"></textarea>

                                                                    </div>
                                                        </div>
                                                <button type="submit" class="btn btn-info">Submit</button>

                                            </form>

                                        </p>
                                    </a>
                            </div>
                        </div>
                    </div>
                <p>

            </div>


</body>

<script src="{% static 'doctor/js/changethreshold.js' %}"></script>
<script src="{% static 'doctor/js/changeContrast.js' %}"></script>
<script src="{% static 'doctor/js/detectEdge.js' %}"></script>
<script src="{% static 'doctor/js/equHist.js' %}"></script>
<script src="{% static 'doctor/js/getResult.js' %}"></script>
<script src="{% static 'doctor/js/slider.js' %}"></script>

</html>

doctor/templates/doctor/pages/print.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Print</title>
</head>
<body>
    <iframe src="{% static 'doctor/printed/MI_report.pdf' %}" width="100%" height="1000"></iframe>
</body>
</html>