assistant/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'assistant'

urlpatterns = [
    path('accounts/login/', never_cache(views.login), name='login'),
    path('accounts/logout/', never_cache(views.logout), name='logout'),
    path('dashboard/', never_cache(views.index), name='dashboard'),
]

home/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'home'

urlpatterns = [
    path('', never_cache(views.index), name='home'),
]

midas_final/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('assistant/', include('assistant.urls')),
    path('doctor/', include('doctor.urls')),
    path('patient/', include('patient.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

assistant/models.py
from django.db import models


# Create your models here.
class AssistantDetails(models.Model):
    userId = models.IntegerField(unique=True)
    name = models.CharField(max_length=25)
    email = models.EmailField(max_length=30)
    password = models.CharField(max_length=50)
    isActive = models.BooleanField(default=False)

    def __str__(self):
        return self.name + "(" + str(self.userId) + ")"

assistant/forms.py
from django import forms
from doctor.models import PendingList


class AssistantLogin(forms.Form):
    user_id = forms.IntegerField(label="User Id", required=True, min_value=1)
    password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput, min_length=8)


class OperatorForm(forms.ModelForm):
    class Meta:
        model = PendingList
        fields = ['doctorId', 'patientId', 'type', 'images']

assistant/views.py
from django.http import HttpResponsePermanentRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import AssistantDetails
from doctor.models import DoctorDetails
from patient.models import PatientDetails
from .forms import AssistantLogin, OperatorForm


# Create your views here.

# Assistant home
def index(request):
    if request.method == "POST":
        form = OperatorForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return HttpResponsePermanentRedirect(reverse('assistant:dashboard'))

    assistant_set = AssistantDetails.objects.all()
    for assistant in assistant_set:
        if assistant.isActive:
            form = OperatorForm()
            context = {"assistant": assistant, "form": form}
            return render(request, 'assistant/pages/dashboard.html', context)

    return HttpResponsePermanentRedirect(reverse('assistant:login'))


#Assistant Login
def login(request):
    # Check Login
    doctor_set = DoctorDetails.objects.all()
    for doctor in doctor_set:
        if doctor.isActive:
            return HttpResponsePermanentRedirect(reverse('doctor:dashboard'))

    patient_set = PatientDetails.objects.all()
    for patient in patient_set:
        if patient.isActive:
            return HttpResponsePermanentRedirect(reverse('patient:dashboard'))

    assistant_set = AssistantDetails.objects.all()
    for assistant in assistant_set:
        if assistant.isActive:
            return HttpResponsePermanentRedirect(reverse('assistant:dashboard'))

    if request.method == 'POST':
        form = AssistantLogin(request.POST)

        if form.is_valid():
            for assistant in assistant_set:
                if assistant.userId == form.cleaned_data['user_id'] and assistant.password == \
                        form.cleaned_data['password']:
                    assistant.isActive = True
                    assistant.save()
                    return HttpResponsePermanentRedirect(reverse('assistant:dashboard'))
        else:
            print("Not working")

    else:
        form = AssistantLogin()

    return render(request, 'assistant/registration/login.html', {'form': form})


#Assistant Logout
def logout(request):
    assistant_set = AssistantDetails.objects.all()
    for assistant in assistant_set:
        if assistant.isActive:
            assistant.isActive = False
            assistant.save()
            return HttpResponsePermanentRedirect(reverse('home:home'))

    return HttpResponsePermanentRedirect(reverse('home:home'))

assistant/templates/assistant/pages/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load crispy_forms_tags %}
<head>
    <meta charset="UTF-8">
    <title>Assistant Form</title>
    <link rel="stylesheet" type="text/css" href="{% static "assistant/css/dashboard.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body style="background-color: #bcbcbe">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home:home' %}">MIDAS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Dashboard for Assistant</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <a class="nav-link" href="#" style="color: white">Welcome, {{ assistant.name }}</a>
      <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'assistant:logout' %}">Logout</a>
    </form>
  </div>
</nav>

    <br><br>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-7">
                        <h1 class="mt-2">Patient Form</h1>
                        <hr class="mt-0 mb-4">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.doctorId|as_crispy_field }}
                            {{ form.patientId|as_crispy_field }}
                            {{ form.type|as_crispy_field }}
                            {{ form.images|as_crispy_field }}
                            <button type="submit" class="btn btn-success">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
</body>
</html>